language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t 1608996/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true 1608996/react-test npm test

after_success:
    - docker build -t 1608996/complex-client ./client
    - docker build -t 1608996/complex-nginx ./nginx
    - docker build -t 1608996/complex-server ./server
    - docker build -t 1608996/complex-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push 1608996/complex-client
    - docker push 1608996/complex-nginx
    - docker push 1608996/complex-server
    - docker push 1608996/complex-worker